[package]
name = "MITRE_lookup"
version = "3.0.2"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
clap = { version = "4.5", features = ["derive"] }
tabled = "0.15"
regex = "1.12.3"
colored = "3.1.1"
